### ISSUE TITLE
Some updates/fixes to do

### ISSUE THREAD

**Issue by franciscozorrilla** [Chrats-Melkonian/mi_cheese#1]
- [x] Replace old models (gapfilled on milk) with updated models sets gapfilled on each media variation + no gapfilling (699c122)
```
├── data
│   ├── Models
│   │   ├── LC.xml
│   │   ├── LLm1.xml
│   │   ├── LLm2.xml
│   │   ├── ST.xml
```
* Add helper scripts (935dfb7)
  - [x] `model_summary_generate.py` to read models and produce individual summaries 
  - [x] `model_summary_compile.sh` script to compile individual summary files into `model_summary.tsv` file
  - [x] `gf_rxns_compile.sh` to read through models and extract gapfilled reaction information into `gf_rxns.tsv` file

**Comment by microbial-cookie** [comment]
Hi Francisco Zorrilla,

Thanks!! But I didn't find it in the code folder....

**Comment by franciscozorrilla** [comment]
Please bear with me as I search for the files/code.
