### ISSUE TITLE
How to use the GEM output of CarveMe to generate these two files?

### ISSUE THREAD

**Issue by microbial-cookie** [Chrats-Melkonian/mi_cheese#2]
Hi franciscozorrilla,

Thanks for the prompt reply. I check the script in your cheese study data/code. And I successfully use the 04_individual_GEM_sims.py to generate the files like (xx.fba and xx.fva). Also, I'd like to know how to generate these files based on the existing GEMs using the cobrapy/reframed + some scripting. I hope you can help me and I'm very grateful for your help.

![image](https://github.com/Chrats-Melkonian/mi_cheese/assets/133230591/f8c90b84-e08a-4840-a142-8653789b3b5f)

**Comment by franciscozorrilla** [comment]
The helper scripts have now been uploaded, please have a look 935dfb7
